# docker-compose.yml
# 指定docker-compose 版本好
version: '3.3'

# 服务
services:
  # 测试服务
  laracom-service:
    image: laracom/service
    # 依赖etcd，etcd 创建后拉起
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    environment:
      # 服务端口
      MICRO_SERVER_ADDRESS: ":9091"
      # 指定服务中心
      MICRO_REGISTEY: "etcd"
      # etcd注册地址
      MICRO_REGISTRY_ADDRESS: "etcd1:2379,etcd2:2379,etcd3:2379"
    ports:
      # 映射服务端口
      - 9091:9091
    networks:
      # 加入网络并指定别名
      laracom-network:
        aliases:
          - "laracom-service"
    # docker-Swarm指定节点类型，实例数
    deploy:
      mode: replicated
      replicas: 1

  # 用户服务
  laracom-user-service:
    image: laracom/userservice
    deoebds_on:
      - laracom-user-db
      - laracom-nats
      - etcd1
      - etcd2
      - etcd3
    ports:
      - 9092:9091
    environment:
      MICRO_SERVER_ADDRESS: ":9091"
      MICRO_REGISTRY: "etcd"
      MICRO_REGISTRY_ADDRESS: "etcd1:2379,etcd2:2379,etcd3:2379"
      MICRO_BROKER: "nats"
      MICRO_BROKER_ADDRESS: "laracom-nats:4222"
      # 用户服务数据库参数
      DB_HOST: "laracom-user-db:3306"
      DB_NAME: "laracom_user"
      DB_USER: "test"
      DB_PASSWORD: "test"
    networks:
      # 加入网络并指定别名
      laracom-network:
        aliases:
          - "laracom-user-service"
    deploy:
      mode: replicated
      replicas: 3

  # 商品服务
  laracom-product-service:
    image: laracom/productservice
    depends_on:
      - laracom-product-db
      - etcd1
      - etcd2
      - etcd3
      - jaeger
    ports:
      - 9093:9091
    environment:
      MICRO_SERVER_ADDRESS: ":9091"
      MICRO_REGISTRY: "etcd"
      MICRO_REGISTRY_ADDRESS: "etcd1:2379,etcd2:2379,etcd3:2379"
      DB_HOST: "laracom-product-db:3306"
      DB_NAME: "laracom_product"
      DB_USER: "product"
      DB_PASSWORD: "test"
      MICRO_LOG_LEVEL: "debug"
    networks:
      laracom_network:
        aliases:
          - "laracom-product-service"
    deploy:
      mode: replicated
      replicas: 3

  # api服务
  laracom-micro-api:
    image: microhq/micro:latest
    environment:
      MICRO_REGISTRY: "etcd"
      MICRO_REGISTRY_ADDRESS: "etcd1:2379,etcd2:2379,etcd3:2379"
    ports:
      - 8080:8080
    networks:
      - laracom_network
    command: api --handler=rpc --namespace=laracom.service
    deploy:
      placement:
        constraints: [node.role == manager]

  # micro注册中心面板
  laracom-web-dashboard:
    image: microhq/micro:latest
    environment:
      MICRO_REGISTRY: "etcd"
      MICRO_REGISTRY_ADDRESS: "etcd1:2379,etcd2:2379,etcd3:2379"
    ports:
      - 8082:8082
    networks:
      - laracom_network
    command: web
    deploy:
      placement:
        constraints: [node.role == manager]

  # 用户服务数据库
  laracom-user-db:
    image: mysql:latest
    ports:
      - 33061:3306
    volumes:
      - db_user_data:/var/lib/mysql
    environment:
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "laracom_user"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - laracom_network
    deploy:
      placement:
        constraints: [node.role == manager]

  # 商品数据库
  laracom-product-db:
    image: mysql:latest
    ports:
      - 33062:3306
    volumes:
      - db_product_data:/var/lib/mysql
    environment:
      MYSQL_USER: "product"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "laracom_product"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - laracom_network
    deploy:
      placement:
        constraints: [node.role == manager]
